### ISSUE TITLE
Run error? Request method 'GET' not supported

### ISSUE THREAD

**Issue by Tao4free** [thombergs/buckpal#13]
Hi, Tom

I am new to java project.

According to the article https://reflectoring.io/spring-boot-gradle-multi-module/
Start the application by `./gradlew bootRun`
And test by input the url in browser `http://localhost:8080/accounts/send/41L/42L/500`.

Here is what I get.
`2020-05-13 11:38:41.481  WARN 41785 --- [nio-8080-exec-3] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]`

Is this the right method to access the buckpal application?
Any comment will be help.

**Comment by thombergs** [comment]
That's because you have to submit it as a `POST` request. You need to use a tool like Postman to send such a request (or build an actual HTML form with `method=POST`). 

See [SendMoneyController](https://github.com/thombergs/buckpal/blob/master/adapters/buckpal-web/src/main/java/io/reflectoring/buckpal/adapter/web/SendMoneyController.java#L20).
