### ISSUE TITLE
Mappers cause JPA entities to "detach"

### ISSUE THREAD

**Issue by yerundev** [thombergs/buckpal#9]
Hi @thombergs 

Thanks for a very good and informative read! Great job!

I have an issue regarding updating existing entities. Since the *JpaEntity objects will be mapped to domain object once read from the database and then back to *JpaEntity objects once they're again passed to the appropriate outgoing port, these objects will no longer be the same objects that were originally retrieved from Hibernate. This causes all the calls with updated entities to *Repositoy.save(jpaEntity) to fail with the javax.persistence.EntityExistsException. What would be the appropriate way of handling this case? 

Thanks!

**Comment by thombergs** [comment]
Hi @yerundev ,

sorry for the late reply.

Yes, mapping JPA entities into domain entities will "undetach" them from the persistence session.

So, on the way back, when we're mapping the domain entities into JPA entities, we'll have to "re-attach" them. This usually works by just storing the ID of the entity in the domain model and, when mapping back into a JPA entity, using the same ID. 

If a JPA entity has an ID, JPA providers should treat it as an existing entity and properly do updates.

I can't say why you get an `EntityExistsException`. JPA is obviously trying to do an `insert` instead of an `update`. There are cases (especially with *-to-many associations) that are more complicated to map. But it's possible. If you share some more code, maybe I can help.

A good thing is that the mapper is part of the persistence layer, where we want to tackle persistence-specific problems like this. This way we can keep problems like this out of the domain layer! 

If we instead use JPA entities directly in the domain layer, we'll eventually have to solve persistence problems in the domain model, which always leads to tangled domain and persistence code.
